### ISSUE TITLE
error in drive

### ISSUE THREAD

**Issue by 1Nu55et1** [JLi69/krab-kart#1]
When you press the "D" key or the right arrow key, the rotation speed is not as fast as when you rotate to the left.

**Comment by JLi69** [comment]
Hello,
This is the code for driving/turning the kart:
```
//Drives kart with keyboard
//acceleration key: acclerate forward
//left key: turn left
//right key: turn right
pub fn drive_kart(
    &mut self,
    events: &Events,
    acceleration_key: Keycode,
    left_key: Keycode,
    right_key: Keycode,
) {
    //Accelerate kart
    if events.key_is_pressed(acceleration_key) {
        //Set kart's speed to be a minimum of 0.5
        if self.speed < 0.5 {
            self.speed = 0.5;
        }

        self.acceleration = 0.7;
    } else {
        //Stop accelecration once key is released
        self.acceleration = 0.0;
    }

    //Rotate left and rotate right
    if events.key_is_pressed(left_key) {
        self.sprite.rotation_speed = -self.speed;
    } else if events.key_is_pressed(right_key) {
        self.sprite.rotation_speed = self.speed;
    } else {
        //None of these keys pressed, don't rotate
        self.sprite.rotation_speed = 0.0;
    }
}
```
and as far as I am aware when ever you press the key to turn left and whenever you press the key to go right, the rotation speed is set to the same value, so could you please elaborate on this issue?

**Comment by 1Nu55et1** [comment]
okay and sorry for the late respond it's because now i readed this.

**Comment by 1Nu55et1** [comment]
The code seems to treat both sides the same, but perhaps there is something else influencing. I don't know, maybe some detail in how the keys are handled or something in the physics of the game (I lean more towards the physics of the game). I came up with a way to verify it. We could measure the actual rotation somehow. How about adding a little debug code to the src / kart.rs file? It could be something like this:

```rust
pub fn drive_kart(
    &mut self,
    events: &Events,
    acceleration_key: Keycode,
    left_key: Keycode,
    right_key: Keycode,
) {
    // ... code ...

    if events.key_is_pressed(left_key) {
        self.sprite.rotation_speed = -self.speed;
        println!("Rotación izquierda: {}", self.sprite.rotation_speed);
    } else if events.key_is_pressed(right_key) {
        self.sprite.rotation_speed = self.speed;
        println!("Rotación derecha: {}", self.sprite.rotation_speed);
    } else {
        self.sprite.rotation_speed = 0.0;
    }
}
```

that in a few words would make it easier to check if the rotation is what causes you trouble

also for your next projects I recommend that you include debug tools more than anything because many times it can make it much easier to solve errors and you could also apply the tdd principle that way you could solve errors and test certain functions of the code without much problem.

I'm sorry if this is not too good, but I am not familiar with the project if you have any questions I would not mind answering if I can.

**Comment by JLi69** [comment]
Thank you for your response!
I'll look into this (soon hopefully) but it's a little late for me right now and I have school so it might be a little before I can get to this.

Also, thanks for the feedback! I mostly made this project when I was first learning Rust and I still kind of consider myself somewhat inexperienced when it comes to programming in general so I admit that I might be doing things the best way. I'll look into including better debugging tools for future projects though I'm personally not a fan of littering my code with print statements. Any further tips?

(¿Prefieres continuar esta discusión en español? Yo aprendí un poco en escuela.)

**Comment by 1Nu55et1** [comment]
There is no problem with speaking in Spanish but I prefer to answer you in English so that you have more understanding or understand more easily. and about that print was more than anything to do it quickly to debug more cleanly and efficiently, I recommend using something like the following (I said I recommend using it because they are the things that I personally use in my day to day):

one. Use a logging system like `log` crate instead of `println!`. This allows you to control the level of detail of messages and easily activate / disable them.

2. Implement a debug mode that you can activate with a flag or environment variable. For example:

```rust
use log::{debug, LevelFilter};

fn main() {
    if std::env::var("DEBUG").is_ok() {
        env_logger::Builder::new().filter_level(LevelFilter::Debug).init();
    }
    // ... rest of the code ...
}
```

3. For your `drive_kart` function, you could do something like this:


```rust
    //Drives kart with keyboard
    //acceleration key: acclerate forward
    //left key: turn left
    //right key: turn right
    pub fn drive_kart(
        &mut self,
        events: &Events,
        acceleration_key: Keycode,
        left_key: Keycode,
        right_key: Keycode,
    ) {
        //Accelerate kart
        if events.key_is_pressed(acceleration_key) {
            //Set kart's speed to be a minimum of 0.5
            if self.speed < 0.5 {
                self.speed = 0.5;
            }

            self.acceleration = 0.7;
        } else {
            //Stop accelecration once key is released
            self.acceleration = 0.0;
        }

        //Rotate left and rotate right
        if events.key_is_pressed(left_key) {
            self.sprite.rotation_speed = -self.speed;
        } else if events.key_is_pressed(right_key) {
            self.sprite.rotation_speed = self.speed;
        } else {
            //None of these keys pressed, don't rotate
            self.sprite.rotation_speed = 0.0;
        }
```

Modify this part to include logging:

```rust
if events.key_is_pressed(left_key) {
    self.sprite.rotation_speed = -self.speed;
    debug!("Rotación izquierda: {}", self.sprite.rotation_speed);
} else if events.key_is_pressed(right_key) {
    self.sprite.rotation_speed = self.speed;
    debug!("Rotación derecha: {}", self.sprite.rotation_speed);
} else {
    self.sprite.rotation_speed = 0.0;
}
```

4. Consider implementing a simple telemetry system that records key data during the game, such as position, speed, and rotation. You could save this data in a file for later analysis.

5. For future projects, consider using profiling tools like `flamegraph` to identify bottlenecks in performance.

Well at least those are the ways that I know and that are the ones that I use, I am possibly forgetting one but well, by the way if you want to ask me a question and that I answer you faster I think the best would be for discord since I am using it a lot lately if you want to add me you can add me as "1nu55et1"

**Comment by 1Nu55et1** [comment]
in case you do not want to add me in discord I will also be attentive to this issue and luck solving the error. ;)

**Comment by JLi69** [comment]
Sorry for the late response but I got a little swamped yesterday.
Anyway, thank you so much for the tips, I'll make note of the them for future projects, they're really helpful :)
By the way, I do actually now think that there is something wrong with the rotation:
```rust
if self.sprite.rotation_speed > self.max_rotation_speed {
    self.sprite.rotation_speed = self.max_rotation_speed;
}
```
This segment of code is for capping the rotation speed but it only checks if the rotation speed exceeds `max_rotation_speed` when its in the positive direction (which I believe is rotating right) and therefore when you turn left, it doesn't cap the rotation speed and it ends up becoming much faster.
The fix is simple: just replace the code with `clamp`
```rust
let min = -self.max_rotation_speed;
let max = self.max_rotation_speed;
self.sprite.rotation_speed = self.sprite.rotation_speed.clamp(min, max);
```
This does seem to fix the issue.
I can't believe I didn't notice this but thank you so much for letting me know of this bug!

**Comment by JLi69** [comment]
Okay, I pushed the changes, the bugfix is in this commit: https://github.com/JLi69/krab-kart/commit/67d759ec1ceaa8b5bda24a68179dc73b02cf895f

I'm not planning on updating this project with debugging tools at the moment though I will try to include them in another project I'm working on (if you want to check it out: https://github.com/JLi69/voxelworld (it's still a work in progress))

Again, thank you for bringing this bug to my attention and providing some pretty awesome advice, do you have anything else you'd like to include or am I good to close this issue?

**Comment by 1Nu55et1** [comment]
No problem, and yes, I will close the issue because that was the only one I found. I would like to collaborate with you on the voxel world project, if you don't mind. I will try to help with optimizations and more. By the way, what version are you recreating?
